### ISSUE TITLE
Issue while running example

### ISSUE THREAD

**Issue by alaindanet** [inSileco/TheseCanevas#1]
Hi Kévin,

Thank you so much for sharing a minimal example of thesis building. I had issues while compiling it.

the first `make` that I did returned this:
    make: Nothing to be done for 'ALL'.

I fixed it in the MakeFile by modifying `ALL:` in `$(ALL):`
Now the MakeFile seems to work the compilation produced this error (from these.log):
    ! Package pdftex.def Error: File `chapitre1/fig/fig1-eps-converted-to.pdf' not found

Thank you for your help!

**Comment by KevCaz** [comment]
Hi Alain, 

I'll look at that ASAP. Hope everything is going well in Montpellier. 

Kev

**Comment by KevCaz** [comment]
A few notes: 

```
make: Nothing to be done for 'ALL'.
```

means there is nothing to do, it's not an erroe. This would make sense if you had a version of the final pdf present in the repo. This should not be the case any longer as I've removed it from the repo (it was not a good idea having it in the repo 😱 ) 

> ALL: in $(ALL):

`ALL:` should work well. If you use`$(ALL):`, it means there is a variable `ALL` you called so. I'd recommend you to stick to use `ALL:`    

```
Error: File `chapitre1/fig/fig1-eps-converted-to.pdf' not found
```

My bad... I forgot to include the file, it should be Ok by now. Note I've changed the name of the file and I now show how to set the figures' size using pandoc mardown => http://pandoc.org/MANUAL.html#extension-link_attributes

Also, I have fixed a couple of unrelated issues I encontered when running the example on my computer. Everything Ok on my side, what about yours?

**Comment by alaindanet** [comment]
Hi Kévin,

thank you for your help. Everything is going fine in Montpellier expect that it will the summer of the thesis writting :).

Okay, I have understood the purpose all `ALL:`. 
The compilation end up with the pdf but `make` continue to return an error:  
```
Makefile:32: recipe for target 'these.pdf' failed
make: *** [these.pdf] Error 1
```

**Comment by KevCaz** [comment]
Hummm... 

I've removed more stuff from the repo, I think it worth trying again even if I doubt it solves your issue. I may not have been clear enough about some basic config (i.e. my OS / version of pdflatex).
Now, the README includes the version of pdflatex I used as well as the OS used for the last successful compilation. 

I would recommend you to do as follow: 

1. git pull 
2. make clean
3. make

If you still get the same error, please write back and indicate:
- your OS (Ubuntu if I remember well, but which version?),
- the pdflatex version you're using,
- if there are any issue with pdflatex => the error should be cast because of one error in the step, basically pdflatex or pandoc


Note that I may have access to a linux machine by the end of the week. 😃

**Comment by KevCaz** [comment]
Hi Alain, 

So, there was an issue with the table labels in the introduction. I've fixed this issue and I am happy to say that the build was successful on my raspberry (Raspbian 8.0 code-named Jessie). I've added a section to explain how I've handled it in the Readme. 

I think closing this issue is Ok now, however don't hesitate if some issues remain on your side. Also, I've removed a couple of typos... I am pretty sure a couple of them remain. If so, please, do not hesitate fixing them and create a PR!

**Comment by alaindanet** [comment]
Hi Kevin,

thank you so much for the additional information that you added.
I am on a Jessie machine as well (with all the old-version packages), I added the stretch repo and upgraded the tex packages, everything is working fine now.

I will not hesitate to contribute myself. Actually, I have begun to modify the .cls according to the prerequisites of the university of Montpellier. Do you have the licence statut of the UQAR .cls ? Whom should I ask permission to use and modify the file ?

Thank again,
Alain

**Comment by KevCaz** [comment]
Hi Alain, 

This is a good question and I am not aware of any licence or any formal copyright. As you must have  already noted there are a couple of comments in the files stating who has done what. I have also edited some of the files. When I did so, I simply added my names saying what I have done and let of other contributors. If you want to contact somebody, I would recomend you to contact Frédéric Cyr, searching his mail on the UQAR website should be easy. 

By the way, if you want to make it suitable for UM, I guess you could/should fork the repo! I"ll be happy to mention what you did on the readme of this repo.

**Comment by KevCaz** [comment]
By the way, I'm not even sure I should put all this under GPL-3. I am not sure it makes sense, I should take a carfeul look at the scope of the FSF licences.

**Comment by alaindanet** [comment]
Ok, I am imagining now to mix some part of code from different cls file mainly from UQAR, [from Paris Saclay](https://github.com/stellasia/thesis-template) and [ from Toulouse](http://tlsflyleaf.onada.fr/index.php).

I will definitly contact them, thank you.

I have already almost reproduced the title page thanks to tikz (What a pain!)
